//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension BankTransactionsApi.Consents {

    public enum GetV1ConsentsByBankIdAuthorise {

        public static let service = APIService<Response>(id: "getV1ConsentsByBankIdAuthorise", tag: "Consents", method: "GET", path: "/v1/consents/{bankId}/authorise", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var bankId: String

                public var countryCode: String?

                public init(bankId: String, countryCode: String? = nil) {
                    self.bankId = bankId
                    self.countryCode = countryCode
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetV1ConsentsByBankIdAuthorise.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(bankId: String, countryCode: String? = nil) {
                let options = Options(bankId: bankId, countryCode: countryCode)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "bankId" + "}", with: "\(self.options.bankId)")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let countryCode = options.countryCode {
                  params["countryCode"] = countryCode
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AccountAuthorisationResponse

            /** Success */
            case status201(AccountAuthorisationResponse)

            /** Bad Request */
            case status400(ErrorResponse)

            public var success: AccountAuthorisationResponse? {
                switch self {
                case .status201(let response): return response
                default: return nil
                }
            }

            public var failure: ErrorResponse? {
                switch self {
                case .status400(let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<AccountAuthorisationResponse, ErrorResponse> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status201(let response): return response
                case .status400(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status201: return 201
                case .status400: return 400
                }
            }

            public var successful: Bool {
                switch self {
                case .status201: return true
                case .status400: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 201: self = try .status201(decoder.decode(AccountAuthorisationResponse.self, from: data))
                case 400: self = try .status400(decoder.decode(ErrorResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
