//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension BankTransactionsApi.Transactions {

    public enum GetV1Transactions {

        public static let service = APIService<Response>(id: "getV1Transactions", tag: "Transactions", method: "GET", path: "/v1/transactions", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var offset: Int?

                public var limit: Int?

                public var sort: String?

                public var merchantName: String?

                public init(offset: Int? = nil, limit: Int? = nil, sort: String? = nil, merchantName: String? = nil) {
                    self.offset = offset
                    self.limit = limit
                    self.sort = sort
                    self.merchantName = merchantName
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetV1Transactions.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(offset: Int? = nil, limit: Int? = nil, sort: String? = nil, merchantName: String? = nil) {
                let options = Options(offset: offset, limit: limit, sort: sort, merchantName: merchantName)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let offset = options.offset {
                  params["offset"] = offset
                }
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let sort = options.sort {
                  params["sort"] = sort
                }
                if let merchantName = options.merchantName {
                  params["merchantName"] = merchantName
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AllTransactionsResponse

            /** Success */
            case status200(AllTransactionsResponse)

            /** Bad Request */
            case status400(ErrorResponse)

            /** Unauthorized */
            case status401(YapilyUnauthorisedResponse)

            /** Not Found */
            case status404(NotFoundResponse)

            public var success: AllTransactionsResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .status400(let response): return response
                case .status401(let response): return response
                case .status404(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status401: return 401
                case .status404: return 404
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status401: return false
                case .status404: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AllTransactionsResponse.self, from: data))
                case 400: self = try .status400(decoder.decode(ErrorResponse.self, from: data))
                case 401: self = try .status401(decoder.decode(YapilyUnauthorisedResponse.self, from: data))
                case 404: self = try .status404(decoder.decode(NotFoundResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
