//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension BankTransactionsApi.Transactions {

    public enum GetV1AccountsByAccountIdTransactions {

        public static let service = APIService<Response>(id: "getV1AccountsByAccountIdTransactions", tag: "Transactions", method: "GET", path: "/v1/accounts/{accountId}/transactions", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public struct Options {

                public var accountId: String

                public var offset: Int?

                public var limit: Int?

                public var sort: String?

                public var merchantName: String?

                public init(accountId: String, offset: Int? = nil, limit: Int? = nil, sort: String? = nil, merchantName: String? = nil) {
                    self.accountId = accountId
                    self.offset = offset
                    self.limit = limit
                    self.sort = sort
                    self.merchantName = merchantName
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: GetV1AccountsByAccountIdTransactions.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(accountId: String, offset: Int? = nil, limit: Int? = nil, sort: String? = nil, merchantName: String? = nil) {
                let options = Options(accountId: accountId, offset: offset, limit: limit, sort: sort, merchantName: merchantName)
                self.init(options: options)
            }

            public override var path: String {
                return super.path.replacingOccurrences(of: "{" + "accountId" + "}", with: "\(self.options.accountId)")
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let offset = options.offset {
                  params["offset"] = offset
                }
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let sort = options.sort {
                  params["sort"] = sort
                }
                if let merchantName = options.merchantName {
                  params["merchantName"] = merchantName
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = OverviewAccountTransactionsResponse

            /** Success */
            case status200(OverviewAccountTransactionsResponse)

            /** Bad Request */
            case status400(ErrorResponse)

            /** Unauthorized */
            case status401(YapilyUnauthorisedResponse)

            /** Forbidden */
            case status403(YapilyForbiddenResponse)

            /** Not Found */
            case status404(NotFoundResponse)

            public var success: OverviewAccountTransactionsResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .status400(let response): return response
                case .status401(let response): return response
                case .status403(let response): return response
                case .status404(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status401: return 401
                case .status403: return 403
                case .status404: return 404
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status401: return false
                case .status403: return false
                case .status404: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(OverviewAccountTransactionsResponse.self, from: data))
                case 400: self = try .status400(decoder.decode(ErrorResponse.self, from: data))
                case 401: self = try .status401(decoder.decode(YapilyUnauthorisedResponse.self, from: data))
                case 403: self = try .status403(decoder.decode(YapilyForbiddenResponse.self, from: data))
                case 404: self = try .status404(decoder.decode(NotFoundResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
