//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

/** Includes all API endpoints to connect users to their banks using Yapily. */
public struct BankTransactionsApi {

    /// Whether to discard any errors when decoding optional properties
    public static var safeOptionalDecoding = false

    /// Whether to remove invalid elements instead of throwing when decoding arrays
    public static var safeArrayDecoding = false

    /// Used to encode Dates when uses as string params
    public static var dateEncodingFormatter = DateFormatter(formatString: "yyyy-MM-dd'T'HH:mm:ssZZZZZ",
                                                            locale: Locale(identifier: "en_US_POSIX"),
                                                            calendar: Calendar(identifier: .gregorian))

    public static let version = "v1"

    public enum Accounts {}
    public enum Banks {}
    public enum CareTips {}
    public enum Consents {}
    public enum Manuals {}
    public enum Transactions {}
    public enum VideoTutorials {}

    public enum Server {

        public static let main = "https://dev-app.airslip.com/bank_transactions"
    }
}
