//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class GoogleSigninRequest: APIModel {

    public var deviceId: String

    public var email: String?

    public var familyName: String?

    public var givenName: String?

    public var locale: String?

    public var name: String?

    public var picture: String?

    public init(deviceId: String, email: String? = nil, familyName: String? = nil, givenName: String? = nil, locale: String? = nil, name: String? = nil, picture: String? = nil) {
        self.deviceId = deviceId
        self.email = email
        self.familyName = familyName
        self.givenName = givenName
        self.locale = locale
        self.name = name
        self.picture = picture
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deviceId = try container.decode("deviceId")
        email = try container.decodeIfPresent("email")
        familyName = try container.decodeIfPresent("family_name")
        givenName = try container.decodeIfPresent("given_name")
        locale = try container.decodeIfPresent("locale")
        name = try container.decodeIfPresent("name")
        picture = try container.decodeIfPresent("picture")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(deviceId, forKey: "deviceId")
        try container.encodeIfPresent(email, forKey: "email")
        try container.encodeIfPresent(familyName, forKey: "family_name")
        try container.encodeIfPresent(givenName, forKey: "given_name")
        try container.encodeIfPresent(locale, forKey: "locale")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(picture, forKey: "picture")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? GoogleSigninRequest else { return false }
      guard self.deviceId == object.deviceId else { return false }
      guard self.email == object.email else { return false }
      guard self.familyName == object.familyName else { return false }
      guard self.givenName == object.givenName else { return false }
      guard self.locale == object.locale else { return false }
      guard self.name == object.name else { return false }
      guard self.picture == object.picture else { return false }
      return true
    }

    public static func == (lhs: GoogleSigninRequest, rhs: GoogleSigninRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
