//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class Link: APIModel {

    public var href: String?

    public var method: String?

    public var rel: String?

    public init(href: String? = nil, method: String? = nil, rel: String? = nil) {
        self.href = href
        self.method = method
        self.rel = rel
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        href = try container.decodeIfPresent("href")
        method = try container.decodeIfPresent("method")
        rel = try container.decodeIfPresent("rel")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(method, forKey: "method")
        try container.encodeIfPresent(rel, forKey: "rel")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? Link else { return false }
      guard self.href == object.href else { return false }
      guard self.method == object.method else { return false }
      guard self.rel == object.rel else { return false }
      return true
    }

    public static func == (lhs: Link, rhs: Link) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
