//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class LoginRequest: APIModel {

    public var deviceId: String

    public var email: String

    public var password: String

    public init(deviceId: String, email: String, password: String) {
        self.deviceId = deviceId
        self.email = email
        self.password = password
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        deviceId = try container.decode("deviceId")
        email = try container.decode("email")
        password = try container.decode("password")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encode(deviceId, forKey: "deviceId")
        try container.encode(email, forKey: "email")
        try container.encode(password, forKey: "password")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? LoginRequest else { return false }
      guard self.deviceId == object.deviceId else { return false }
      guard self.email == object.email else { return false }
      guard self.password == object.password else { return false }
      return true
    }

    public static func == (lhs: LoginRequest, rhs: LoginRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
