//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class UpdateBiometricRequest: APIModel {

    public var biometricOn: Bool?

    public init(biometricOn: Bool? = nil) {
        self.biometricOn = biometricOn
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        biometricOn = try container.decodeIfPresent("biometricOn")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(biometricOn, forKey: "biometricOn")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? UpdateBiometricRequest else { return false }
      guard self.biometricOn == object.biometricOn else { return false }
      return true
    }

    public static func == (lhs: UpdateBiometricRequest, rhs: UpdateBiometricRequest) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
