//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AccountsResponse: APIModel {

    public var accounts: [AccountResponse]?

    public var links: [Link]?

    public init(accounts: [AccountResponse]? = nil, links: [Link]? = nil) {
        self.accounts = accounts
        self.links = links
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        accounts = try container.decodeArrayIfPresent("accounts")
        links = try container.decodeArrayIfPresent("links")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(accounts, forKey: "accounts")
        try container.encodeIfPresent(links, forKey: "links")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AccountsResponse else { return false }
      guard self.accounts == object.accounts else { return false }
      guard self.links == object.links else { return false }
      return true
    }

    public static func == (lhs: AccountsResponse, rhs: AccountsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
