//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AccountAuthorisationResponse: APIModel {

    public var authorisationUrl: String?

    public init(authorisationUrl: String? = nil) {
        self.authorisationUrl = authorisationUrl
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        authorisationUrl = try container.decodeIfPresent("authorisationUrl")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(authorisationUrl, forKey: "authorisationUrl")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AccountAuthorisationResponse else { return false }
      guard self.authorisationUrl == object.authorisationUrl else { return false }
      return true
    }

    public static func == (lhs: AccountAuthorisationResponse, rhs: AccountAuthorisationResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
