//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AllNewTransactionsResponse: APIModel {

    public var links: [Link]?

    public var transactions: [AllTransactionResponse]?

    public init(links: [Link]? = nil, transactions: [AllTransactionResponse]? = nil) {
        self.links = links
        self.transactions = transactions
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        links = try container.decodeArrayIfPresent("links")
        transactions = try container.decodeArrayIfPresent("transactions")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(links, forKey: "links")
        try container.encodeIfPresent(transactions, forKey: "transactions")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AllNewTransactionsResponse else { return false }
      guard self.links == object.links else { return false }
      guard self.transactions == object.transactions else { return false }
      return true
    }

    public static func == (lhs: AllNewTransactionsResponse, rhs: AllNewTransactionsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
