//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class AllTransactionsResponse: APIModel {

    public var links: [Link]?

    public var pagedData: AllTransactionResponsePagedResult?

    public init(links: [Link]? = nil, pagedData: AllTransactionResponsePagedResult? = nil) {
        self.links = links
        self.pagedData = pagedData
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        links = try container.decodeArrayIfPresent("links")
        pagedData = try container.decodeIfPresent("pagedData")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(links, forKey: "links")
        try container.encodeIfPresent(pagedData, forKey: "pagedData")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? AllTransactionsResponse else { return false }
      guard self.links == object.links else { return false }
      guard self.pagedData == object.pagedData else { return false }
      return true
    }

    public static func == (lhs: AllTransactionsResponse, rhs: AllTransactionsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
