//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class BanksResponse: APIModel {

    public var banks: [BankResponse]?

    public var links: [Link]?

    public init(banks: [BankResponse]? = nil, links: [Link]? = nil) {
        self.banks = banks
        self.links = links
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        banks = try container.decodeArrayIfPresent("banks")
        links = try container.decodeArrayIfPresent("links")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(banks, forKey: "banks")
        try container.encodeIfPresent(links, forKey: "links")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? BanksResponse else { return false }
      guard self.banks == object.banks else { return false }
      guard self.links == object.links else { return false }
      return true
    }

    public static func == (lhs: BanksResponse, rhs: BanksResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
