//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ManualsResponse: APIModel {

    public var links: [Link]?

    public var userManuals: [ManualResponse]?

    public init(links: [Link]? = nil, userManuals: [ManualResponse]? = nil) {
        self.links = links
        self.userManuals = userManuals
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        links = try container.decodeArrayIfPresent("links")
        userManuals = try container.decodeArrayIfPresent("userManuals")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(links, forKey: "links")
        try container.encodeIfPresent(userManuals, forKey: "userManuals")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ManualsResponse else { return false }
      guard self.links == object.links else { return false }
      guard self.userManuals == object.userManuals else { return false }
      return true
    }

    public static func == (lhs: ManualsResponse, rhs: ManualsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
