//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class ProductCareTipsResponse: APIModel {

    public var descriptions: [String]?

    public var links: [Link]?

    public var merchantName: String?

    public var productItem: String?

    public init(descriptions: [String]? = nil, links: [Link]? = nil, merchantName: String? = nil, productItem: String? = nil) {
        self.descriptions = descriptions
        self.links = links
        self.merchantName = merchantName
        self.productItem = productItem
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        descriptions = try container.decodeArrayIfPresent("descriptions")
        links = try container.decodeArrayIfPresent("links")
        merchantName = try container.decodeIfPresent("merchantName")
        productItem = try container.decodeIfPresent("productItem")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(descriptions, forKey: "descriptions")
        try container.encodeIfPresent(links, forKey: "links")
        try container.encodeIfPresent(merchantName, forKey: "merchantName")
        try container.encodeIfPresent(productItem, forKey: "productItem")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? ProductCareTipsResponse else { return false }
      guard self.descriptions == object.descriptions else { return false }
      guard self.links == object.links else { return false }
      guard self.merchantName == object.merchantName else { return false }
      guard self.productItem == object.productItem else { return false }
      return true
    }

    public static func == (lhs: ProductCareTipsResponse, rhs: ProductCareTipsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
