//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public class VideoTutorialsResponse: APIModel {

    public var links: [Link]?

    public var videoTutorials: [VideoTutorialResponse]?

    public init(links: [Link]? = nil, videoTutorials: [VideoTutorialResponse]? = nil) {
        self.links = links
        self.videoTutorials = videoTutorials
    }

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        links = try container.decodeArrayIfPresent("links")
        videoTutorials = try container.decodeArrayIfPresent("videoTutorials")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(links, forKey: "links")
        try container.encodeIfPresent(videoTutorials, forKey: "videoTutorials")
    }

    public func isEqual(to object: Any?) -> Bool {
      guard let object = object as? VideoTutorialsResponse else { return false }
      guard self.links == object.links else { return false }
      guard self.videoTutorials == object.videoTutorials else { return false }
      return true
    }

    public static func == (lhs: VideoTutorialsResponse, rhs: VideoTutorialsResponse) -> Bool {
        return lhs.isEqual(to: rhs)
    }
}
