name: iOS App Build and Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test App
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Build and Test App
        uses: maierj/fastlane-action@v1.4.0
        with:
            lane: 'buildandtest'
        env:
            FASTLANE_USER: ${{ secrets.APPLEID_USERNAME }}
            FASTLANE_PASSWORD: ${{ secrets.APPLEID_PASSWORD }}
            FASTLANE_SESSION: ${{ secrets.APPLEID_SESSION }}
            FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLEID_APP_SPECIFIC }}
            MATCH_PASSWORD: ${{ secrets.IOS_KEYS }}
            REPO_TOKEN: ${{ secrets.REPO_TOKEN_BASE64 }}