//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

extension BankTransactionsApi.Accounts {

    public enum GetV1Accounts {

        public static let service = APIService<Response>(id: "getV1Accounts", tag: "Accounts", method: "GET", path: "/v1/accounts", hasBody: false, securityRequirements: [])

        public final class Request: APIRequest<Response> {

            public init() {
                super.init(service: GetV1Accounts.service)
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = AccountsResponse

            /** Success */
            case status200(AccountsResponse)

            /** Bad Request */
            case status400(ErrorResponse)

            /** Unauthorized */
            case status401(YapilyUnauthorisedResponse)

            /** Forbidden */
            case status403(YapilyForbiddenResponse)

            /** Client Error */
            case status424(YapilyFailedDependencyResponse)

            public var success: AccountsResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .status400(let response): return response
                case .status401(let response): return response
                case .status403(let response): return response
                case .status424(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status401: return 401
                case .status403: return 403
                case .status424: return 424
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status401: return false
                case .status403: return false
                case .status424: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(AccountsResponse.self, from: data))
                case 400: self = try .status400(decoder.decode(ErrorResponse.self, from: data))
                case 401: self = try .status401(decoder.decode(YapilyUnauthorisedResponse.self, from: data))
                case 403: self = try .status403(decoder.decode(YapilyForbiddenResponse.self, from: data))
                case 424: self = try .status424(decoder.decode(YapilyFailedDependencyResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
